# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_device', models.CharField(max_length=5)),
                ('id_subsensor', models.IntegerField(max_length=3)),
                ('sensor_datatime', models.DateTimeField(auto_now=True)),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='sensors.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_terreno_long', models.DecimalField(decimal_places=3, max_digits=8)),
                ('pos_terreno_lat', models.DecimalField(decimal_places=3, max_digits=8)),
                ('user_terreno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
