# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreno',
            name='pos_terreno_lat',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='terreno',
            name='pos_terreno_long',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
