# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20170702_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='temp_master',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
